CREATE TABLE CITIZEN
(
    ID         UUID      NOT NULL,
    FIRSTNAME  VARCHAR   NOT NULL,
    LASTNAME   VARCHAR   NOT NULL,
    CITY       VARCHAR   NOT NULL,
    NATIONALID VARCHAR   NOT NULL,
    CREATED_ON TIMESTAMP NOT NULL,
    UPDATED_ON TIMESTAMP NOT NULL,
    PRIMARY KEY (ID)
);