CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TABLE CITIZEN
(
    CITIZENID         UUID      NOT NULL DEFAULT uuid_generate_v1(),
    FIRSTNAME  VARCHAR   NOT NULL,
    LASTNAME   VARCHAR   NOT NULL,
    CITY       VARCHAR   NOT NULL,
    NATIONALID VARCHAR   NOT NULL,
    CREATED_ON TIMESTAMP NOT NULL,
    PRIMARY KEY (CITIZENID)
);